#
# Reference
# https://bukkit.gamepedia.com/Plugin_YAML
#
name: ScavengerHunt
main: net.peacefulcraft.scavengerhunt.ScavengerHunt
version: 0.0.1
api-version: 1.16
website: https://www.peacefulcraft.net/
depend: []
softdepend: []

commands:
  scavengerhunt:
    aliases: [ 'sh' ]
    description: Main command for plugin
    permission-message: Permissions are required to use this command
    usage: /<command> to use command

permissions:
  scavengerhunt.*:
    description: Gives access to all templateus commands
    children:
      scavengerhunt.example: true
  scavengerhunt.example:
    description: Gives access to tempateus' example command
    default: op
